-- Seed daily checklist items
insert into public.checklist_items (name, description, category, subcategory, sort_order) values
  -- Duty Roulettes
  ('Duty Roulette: Expert', 'High-level tomestones', 'daily', 'duty_roulette', 10),
  ('Duty Roulette: Level 90 Dungeons', 'Level cap dungeons', 'daily', 'duty_roulette', 20),
  ('Duty Roulette: Level 50/60/70/80 Dungeons', '', 'daily', 'duty_roulette', 30),
  ('Duty Roulette: Leveling', 'Exp bonus', 'daily', 'duty_roulette', 40),
  ('Duty Roulette: Main Scenario', 'Tomestones + exp', 'daily', 'duty_roulette', 50),
  ('Duty Roulette: Trials', '', 'daily', 'duty_roulette', 60),
  ('Duty Roulette: Alliance Raids', 'Tomestones bonus', 'daily', 'duty_roulette', 70),
  ('Duty Roulette: Normal Raids', '', 'daily', 'duty_roulette', 80),
  ('Duty Roulette: Frontline', 'Wolf Marks + PvP EXP', 'daily', 'duty_roulette', 90),
  ('Duty Roulette: Guildhest', '', 'daily', 'duty_roulette', 100),
  ('Duty Roulette: Mentor', 'Requires Mentor status', 'daily', 'duty_roulette', 110),
  -- Cactpot
  ('Mini Cactpot 1/3', 'Buy a scratch ticket at the Cactpot Broker', 'daily', 'cactpot', 200),
  ('Mini Cactpot 2/3', 'Buy a scratch ticket at the Cactpot Broker', 'daily', 'cactpot', 210),
  ('Mini Cactpot 3/3', 'Buy a scratch ticket at the Cactpot Broker', 'daily', 'cactpot', 220),
  -- Hunts
  ('Daily Hunt Bills', '3 hunts from your Grand Company', 'daily', 'hunt', 300),
  -- Beast Tribes
  ('Beast Tribe: Amalj''aa', '3 quests (ARR)', 'daily', 'beast_tribe', 400),
  ('Beast Tribe: Sylph', '3 quests (ARR)', 'daily', 'beast_tribe', 410),
  ('Beast Tribe: Kobold', '3 quests (ARR)', 'daily', 'beast_tribe', 420),
  ('Beast Tribe: Sahagin', '3 quests (ARR)', 'daily', 'beast_tribe', 430),
  ('Beast Tribe: Ixal', '3 quests (ARR, Crafters)', 'daily', 'beast_tribe', 440),
  ('Beast Tribe: Vanu Vanu', '3 quests (HW)', 'daily', 'beast_tribe', 450),
  ('Beast Tribe: Vath', '3 quests (HW)', 'daily', 'beast_tribe', 460),
  ('Beast Tribe: Moogles', '3 quests (HW, Crafters)', 'daily', 'beast_tribe', 470),
  ('Beast Tribe: Kojin', '3 quests (SB)', 'daily', 'beast_tribe', 480),
  ('Beast Tribe: Ananta', '3 quests (SB)', 'daily', 'beast_tribe', 490),
  ('Beast Tribe: Namazu', '3 quests (SB, DoH/DoL)', 'daily', 'beast_tribe', 500),
  ('Beast Tribe: Pixie', '3 quests (ShB)', 'daily', 'beast_tribe', 510),
  ('Beast Tribe: Qitari', '3 quests (ShB, DoH/DoL)', 'daily', 'beast_tribe', 520),
  ('Beast Tribe: Dwarf', '3 quests (ShB, Crafters)', 'daily', 'beast_tribe', 530),
  ('Beast Tribe: Arkasodara', '3 quests (EW)', 'daily', 'beast_tribe', 540),
  ('Beast Tribe: Omicron', '3 quests (EW, DoH/DoL)', 'daily', 'beast_tribe', 550),
  ('Beast Tribe: Loporrits', '3 quests (EW, Crafters)', 'daily', 'beast_tribe', 560),
  ('Beast Tribe: Pelupelu', '3 quests (DT)', 'daily', 'beast_tribe', 570),
  ('Beast Tribe: Moblins', '3 quests (DT, DoH/DoL)', 'daily', 'beast_tribe', 580),
  ('Beast Tribe: Rroneek', '3 quests (DT)', 'daily', 'beast_tribe', 590),
  -- Other
  ('Custom Deliveries', 'Up to 6 HQ deliveries to your client', 'daily', 'other', 700),
  ('Squadron Mission', 'Send your squadron on a mission', 'daily', 'other', 710),
  ('GC Expert Delivery', 'Turn in HQ items for seals', 'daily', 'other', 720),
  -- Weekly items
  ('Windhurst: The Third Walk', 'Weekly tomestone bonus from alliance raid', 'weekly', 'raids', 10),
  ('AAC Heavyweight M1', 'Vamp Fatale', 'weekly', 'raids', 20),
  ('AAC Heavyweight M2', 'Red Hot and Deep Blue', 'weekly', 'raids', 30),
  ('AAC Heavyweight M3', 'The Tyrant', 'weekly', 'raids', 40),
  ('AAC Heavyweight M4', 'Lindwurm', 'weekly', 'raids', 50),
  ('AAC Heavyweight M1 (Savage)', 'M9S · Vamp Fatale', 'weekly', 'raids', 60),
  ('AAC Heavyweight M2 (Savage)', 'M10S · Red Hot and Deep Blue', 'weekly', 'raids', 70),
  ('AAC Heavyweight M3 (Savage)', 'M11S · The Tyrant', 'weekly', 'raids', 80),
  ('AAC Heavyweight M4 (Savage)', 'M12S · Lindwurm', 'weekly', 'raids', 90),
  ('Jumbo Cactpot', 'Buy a Jumbo Cactpot ticket (drawn Saturday 20:00 JST)', 'weekly', 'cactpot', 200),
  ('Wondrous Tails Book', 'Complete your Wondrous Tails book (16 stickers)', 'weekly', 'other', 300),
  ('Weekly Hunt Bills', 'S-rank and A-rank weekly marks', 'weekly', 'hunt', 310),
  ('Challenge Log', 'Complete challenges for bonus EXP and rewards', 'weekly', 'other', 320),
  ('Treasure Maps', 'Dig up your treasure maps', 'weekly', 'other', 330),
  ('Custom Deliveries (Weekly Cap)', '12 deliveries per week across all clients', 'weekly', 'other', 340);
